CREATE DATABASE IF NOT EXISTS agri_production DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE agri_production;

CREATE TABLE IF NOT EXISTS agri_prod_farm (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    farm_code VARCHAR(64) NOT NULL UNIQUE COMMENT '农场编码',
    farm_name VARCHAR(128) NOT NULL COMMENT '农场名称',
    farm_type VARCHAR(32) COMMENT '农场类型',
    legal_person VARCHAR(64) COMMENT '法人',
    contact_phone VARCHAR(32) COMMENT '联系电话',
    province VARCHAR(64) COMMENT '省份',
    city VARCHAR(64) COMMENT '城市',
    district VARCHAR(64) COMMENT '区县',
    address VARCHAR(256) COMMENT '详细地址',
    longitude DECIMAL(12,8) COMMENT '经度',
    latitude DECIMAL(12,8) COMMENT '纬度',
    total_area DECIMAL(15,4) COMMENT '总面积',
    plot_count INT DEFAULT 0 COMMENT '地块数量',
    farm_type_detail VARCHAR(128) COMMENT '农场类型详情',
    main_products VARCHAR(256) COMMENT '主要产品',
    certifications VARCHAR(512) COMMENT '认证证书',
    certification_expire_date DATE COMMENT '认证有效期',
    certifications_json TEXT COMMENT '认证信息JSON',
    logo_url VARCHAR(512) COMMENT 'Logo URL',
    intro TEXT COMMENT '农场简介',
    register_date DATE COMMENT '注册日期',
    audit_status VARCHAR(32) DEFAULT 'pending' COMMENT '审核状态',
    status VARCHAR(32) DEFAULT 'inactive' COMMENT '状态',
    del_flag TINYINT DEFAULT 0 COMMENT '删除标记',
    tenant_id VARCHAR(64) COMMENT '租户ID',
    create_by VARCHAR(64) COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) COMMENT '更新人',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    remark VARCHAR(512) COMMENT '备注',
    INDEX idx_farm_code (farm_code),
    INDEX idx_tenant_id (tenant_id),
    INDEX idx_audit_status (audit_status),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='农场表';

CREATE TABLE IF NOT EXISTS agri_prod_plot (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    farm_id BIGINT NOT NULL COMMENT '农场ID',
    plot_code VARCHAR(64) NOT NULL UNIQUE COMMENT '地块编码',
    plot_name VARCHAR(128) NOT NULL COMMENT '地块名称',
    plot_type VARCHAR(32) COMMENT '地块类型',
    area DECIMAL(15,4) COMMENT '面积',
    area_unit VARCHAR(16) DEFAULT '亩' COMMENT '面积单位',
    location_lat DECIMAL(12,8) COMMENT '纬度',
    location_lng DECIMAL(12,8) COMMENT '经度',
    location_name VARCHAR(128) COMMENT '位置名称',
    boundary_json TEXT COMMENT '边界JSON',
    soil_type VARCHAR(64) COMMENT '土壤类型',
    soil_ph DECIMAL(5,2) COMMENT '土壤pH值',
    soil_organic DECIMAL(10,4) COMMENT '有机质含量',
    soil_nitrogen DECIMAL(10,4) COMMENT '氮含量',
    soil_phosphorus DECIMAL(10,4) COMMENT '磷含量',
    soil_potassium DECIMAL(10,4) COMMENT '钾含量',
    water_source VARCHAR(128) COMMENT '水源',
    irrigation_type VARCHAR(64) COMMENT '灌溉类型',
    drainage_type VARCHAR(64) COMMENT '排水类型',
    current_crop VARCHAR(128) COMMENT '当前作物',
    crop_variety VARCHAR(128) COMMENT '品种',
    planting_date DATE COMMENT '种植日期',
    expected_harvest_date DATE COMMENT '预计收获日期',
    growth_stage VARCHAR(64) COMMENT '生长阶段',
    status VARCHAR(32) DEFAULT 'active' COMMENT '状态',
    sort_order INT DEFAULT 0 COMMENT '排序',
    del_flag TINYINT DEFAULT 0 COMMENT '删除标记',
    tenant_id VARCHAR(64) COMMENT '租户ID',
    create_by VARCHAR(64) COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) COMMENT '更新人',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    remark VARCHAR(512) COMMENT '备注',
    INDEX idx_farm_id (farm_id),
    INDEX idx_plot_code (plot_code),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='地块表';

CREATE TABLE IF NOT EXISTS agri_prod_task (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    task_code VARCHAR(64) NOT NULL UNIQUE COMMENT '任务编码',
    task_name VARCHAR(128) NOT NULL COMMENT '任务名称',
    farm_id BIGINT COMMENT '农场ID',
    task_type VARCHAR(32) COMMENT '任务类型',
    task_source VARCHAR(32) COMMENT '任务来源',
    plot_id BIGINT COMMENT '地块ID',
    plot_ids VARCHAR(512) COMMENT '关联地块ID列表',
    plan_id BIGINT COMMENT '计划ID',
    template_id BIGINT COMMENT '模板ID',
    plan_date DATE COMMENT '计划日期',
    plan_executor VARCHAR(64) COMMENT '计划执行人',
    actual_executor VARCHAR(64) COMMENT '实际执行人',
    priority VARCHAR(16) DEFAULT 'normal' COMMENT '优先级',
    status VARCHAR(32) DEFAULT 'pending' COMMENT '状态',
    completion_rate DECIMAL(5,2) DEFAULT 0 COMMENT '完成率',
    plan_start_time DATETIME COMMENT '计划开始时间',
    plan_end_time DATETIME COMMENT '计划结束时间',
    actual_start_time DATETIME COMMENT '实际开始时间',
    actual_end_time DATETIME COMMENT '实际结束时间',
    task_desc TEXT COMMENT '任务描述',
    inputs_json TEXT COMMENT '投入品JSON',
    expected_output VARCHAR(512) COMMENT '预期产出',
    related_task_id BIGINT COMMENT '关联任务ID',
    chain_status VARCHAR(32) DEFAULT 'pending' COMMENT '上链状态',
    chain_tx_hash VARCHAR(256) COMMENT '链上交易哈希',
    del_flag TINYINT DEFAULT 0 COMMENT '删除标记',
    tenant_id VARCHAR(64) COMMENT '租户ID',
    create_by VARCHAR(64) COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) COMMENT '更新人',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    remark VARCHAR(512) COMMENT '备注',
    INDEX idx_farm_id (farm_id),
    INDEX idx_task_code (task_code),
    INDEX idx_status (status),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='任务表';

CREATE TABLE IF NOT EXISTS agri_prod_task_template (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    template_code VARCHAR(64) NOT NULL UNIQUE COMMENT '模板编码',
    template_name VARCHAR(128) NOT NULL COMMENT '模板名称',
    template_type VARCHAR(32) COMMENT '模板类型',
    crop_category VARCHAR(64) COMMENT '作物类别',
    crop_name VARCHAR(128) COMMENT '作物名称',
    task_type VARCHAR(32) COMMENT '任务类型',
    growth_stage VARCHAR(64) COMMENT '生长阶段',
    description TEXT COMMENT '描述',
    template_content TEXT COMMENT '模板内容',
    recommended_duration_hours INT COMMENT '推荐时长(小时)',
    required_inputs TEXT COMMENT '必需投入品',
    optional_inputs TEXT COMMENT '可选投入品',
    is_system TINYINT DEFAULT 0 COMMENT '是否系统模板',
    use_count INT DEFAULT 0 COMMENT '使用次数',
    sort_order INT DEFAULT 0 COMMENT '排序',
    status VARCHAR(32) DEFAULT 'active' COMMENT '状态',
    del_flag TINYINT DEFAULT 0 COMMENT '删除标记',
    tenant_id VARCHAR(64) COMMENT '租户ID',
    create_by VARCHAR(64) COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) COMMENT '更新人',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    remark VARCHAR(512) COMMENT '备注',
    INDEX idx_template_code (template_code),
    INDEX idx_crop_category (crop_category),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='任务模板表';

CREATE TABLE IF NOT EXISTS agri_prod_facility (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    farm_id BIGINT NOT NULL COMMENT '农场ID',
    facility_code VARCHAR(64) NOT NULL UNIQUE COMMENT '设施编码',
    facility_name VARCHAR(128) NOT NULL COMMENT '设施名称',
    facility_type VARCHAR(64) COMMENT '设施类型',
    spec_model VARCHAR(128) COMMENT '规格型号',
    manufacturer VARCHAR(128) COMMENT '制造商',
    build_date DATE COMMENT '建造日期',
    area DECIMAL(15,4) COMMENT '面积',
    area_unit VARCHAR(16) DEFAULT '平方米' COMMENT '面积单位',
    location VARCHAR(256) COMMENT '位置',
    capacity INT COMMENT '容量',
    linked_plot_id BIGINT COMMENT '关联地块ID',
    linked_device_ids VARCHAR(512) COMMENT '关联设备ID列表',
    install_date DATE COMMENT '安装日期',
    maintenance_date DATE COMMENT '维护日期',
    depreciation_years INT COMMENT '折旧年限',
    original_value DECIMAL(18,4) COMMENT '原值',
    status VARCHAR(32) DEFAULT 'active' COMMENT '状态',
    del_flag TINYINT DEFAULT 0 COMMENT '删除标记',
    tenant_id VARCHAR(64) COMMENT '租户ID',
    create_by VARCHAR(64) COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) COMMENT '更新人',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    remark VARCHAR(512) COMMENT '备注',
    INDEX idx_farm_id (farm_id),
    INDEX idx_facility_code (facility_code),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='设施设备表';

CREATE TABLE IF NOT EXISTS agri_prod_planting_plan (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    plan_code VARCHAR(64) NOT NULL UNIQUE COMMENT '计划编码',
    plan_name VARCHAR(128) NOT NULL COMMENT '计划名称',
    farm_id BIGINT NOT NULL COMMENT '农场ID',
    plan_year INT COMMENT '计划年份',
    plan_season VARCHAR(32) COMMENT '计划季节',
    plan_status VARCHAR(32) DEFAULT 'draft' COMMENT '计划状态',
    total_area DECIMAL(15,4) COMMENT '总面积',
    total_budget DECIMAL(18,4) COMMENT '总预算',
    expected_output DECIMAL(18,4) COMMENT '预期产出',
    expected_profit DECIMAL(18,4) COMMENT '预期收益',
    start_date DATE COMMENT '开始日期',
    end_date DATE COMMENT '结束日期',
    plan_summary TEXT COMMENT '计划摘要',
    approval_comment TEXT COMMENT '审批意见',
    approver VARCHAR(64) COMMENT '审批人',
    approval_time DATETIME COMMENT '审批时间',
    del_flag TINYINT DEFAULT 0 COMMENT '删除标记',
    tenant_id VARCHAR(64) COMMENT '租户ID',
    create_by VARCHAR(64) COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) COMMENT '更新人',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    remark VARCHAR(512) COMMENT '备注',
    INDEX idx_farm_id (farm_id),
    INDEX idx_plan_code (plan_code),
    INDEX idx_plan_year (plan_year),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='种植计划表';

CREATE TABLE IF NOT EXISTS agri_prod_soil_record (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    plot_id BIGINT NOT NULL COMMENT '地块ID',
    record_no VARCHAR(64) NOT NULL UNIQUE COMMENT '记录编号',
    sample_no VARCHAR(64) COMMENT '样品编号',
    sample_date DATE COMMENT '采样日期',
    sample_location VARCHAR(256) COMMENT '采样位置',
    lab_name VARCHAR(128) COMMENT '检测机构',
    test_date DATE COMMENT '检测日期',
    ph DECIMAL(5,2) COMMENT 'pH值',
    organic_matter DECIMAL(10,4) COMMENT '有机质',
    total_nitrogen DECIMAL(10,4) COMMENT '全氮',
    available_phosphorus DECIMAL(10,4) COMMENT '有效磷',
    available_potassium DECIMAL(10,4) COMMENT '速效钾',
    hydrolyzable_nitrogen DECIMAL(10,4) COMMENT '水解氮',
    moisture DECIMAL(10,4) COMMENT '含水率',
    heavy_metal_lead DECIMAL(10,4) COMMENT '重金属铅',
    heavy_metal_cadmium DECIMAL(10,4) COMMENT '重金属镉',
    heavy_metal_mercury DECIMAL(10,4) COMMENT '重金属汞',
    heavy_metal_arsenic DECIMAL(10,4) COMMENT '重金属砷',
    health_score DECIMAL(5,2) COMMENT '健康评分',
    health_level VARCHAR(32) COMMENT '健康等级',
    improvement_suggestion TEXT COMMENT '改良建议',
    report_url VARCHAR(512) COMMENT '报告URL',
    del_flag TINYINT DEFAULT 0 COMMENT '删除标记',
    tenant_id VARCHAR(64) COMMENT '租户ID',
    create_by VARCHAR(64) COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) COMMENT '更新人',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_plot_id (plot_id),
    INDEX idx_record_no (record_no),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='土壤检测记录表';

CREATE TABLE IF NOT EXISTS agri_prod_input_product (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    product_code VARCHAR(64) NOT NULL UNIQUE COMMENT '产品编码',
    product_name VARCHAR(128) NOT NULL COMMENT '产品名称',
    category VARCHAR(64) COMMENT '类别',
    sub_category VARCHAR(64) COMMENT '子类别',
    spec VARCHAR(128) COMMENT '规格',
    unit VARCHAR(32) COMMENT '单位',
    pack_size VARCHAR(64) COMMENT '包装规格',
    manufacturer VARCHAR(128) COMMENT '生产厂家',
    registration_no VARCHAR(128) COMMENT '登记证号',
    production_license VARCHAR(128) COMMENT '生产许可证',
    valid_until DATE COMMENT '有效期至',
    storage_condition VARCHAR(256) COMMENT '储存条件',
    hazard_level VARCHAR(32) COMMENT '危险等级',
    forbidden_use VARCHAR(512) COMMENT '禁用范围',
    usage_instruction TEXT COMMENT '使用说明',
    dosage_recommendation VARCHAR(512) COMMENT '推荐剂量',
    withdrawal_period INT COMMENT '休药期(天)',
    forbidden TINYINT DEFAULT 0 COMMENT '是否禁用',
    forbidden_reason VARCHAR(512) COMMENT '禁用原因',
    safety_stock DECIMAL(15,4) COMMENT '安全库存',
    unit_cost DECIMAL(12,4) COMMENT '单价',
    bar_code VARCHAR(64) COMMENT '条码',
    image_url VARCHAR(512) COMMENT '图片URL',
    status VARCHAR(32) DEFAULT 'active' COMMENT '状态',
    del_flag TINYINT DEFAULT 0 COMMENT '删除标记',
    tenant_id VARCHAR(64) COMMENT '租户ID',
    create_by VARCHAR(64) COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) COMMENT '更新人',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    remark VARCHAR(512) COMMENT '备注',
    INDEX idx_product_code (product_code),
    INDEX idx_category (category),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='投入品产品表';

CREATE TABLE IF NOT EXISTS agri_prod_input_inbound (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    inbound_no VARCHAR(64) NOT NULL UNIQUE COMMENT '入库单号',
    product_id BIGINT COMMENT '产品ID',
    product_name VARCHAR(128) COMMENT '产品名称',
    batch_no VARCHAR(64) COMMENT '批次号',
    inbound_quantity DECIMAL(15,4) COMMENT '入库数量',
    unit VARCHAR(32) COMMENT '单位',
    unit_price DECIMAL(12,4) COMMENT '单价',
    total_amount DECIMAL(18,4) COMMENT '总金额',
    supplier_name VARCHAR(128) COMMENT '供应商名称',
    supplier_contact VARCHAR(64) COMMENT '供应商联系人',
    purchase_order_no VARCHAR(64) COMMENT '采购单号',
    inbound_date DATE COMMENT '入库日期',
    inbound_type VARCHAR(32) COMMENT '入库类型',
    warehouse_location VARCHAR(128) COMMENT '库位',
    production_date DATE COMMENT '生产日期',
    valid_until DATE COMMENT '有效期至',
    quantity_check TINYINT DEFAULT 0 COMMENT '数量验收',
    quality_check TINYINT DEFAULT 0 COMMENT '质量验收',
    handler VARCHAR(64) COMMENT '经手人',
    approver VARCHAR(64) COMMENT '审批人',
    approval_time DATETIME COMMENT '审批时间',
    approval_status VARCHAR(32) DEFAULT 'pending' COMMENT '审批状态',
    remark VARCHAR(512) COMMENT '备注',
    del_flag TINYINT DEFAULT 0 COMMENT '删除标记',
    tenant_id VARCHAR(64) COMMENT '租户ID',
    create_by VARCHAR(64) COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) COMMENT '更新人',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_inbound_no (inbound_no),
    INDEX idx_batch_no (batch_no),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='投入品入库表';

CREATE TABLE IF NOT EXISTS agri_prod_input_outbound (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    outbound_no VARCHAR(64) NOT NULL UNIQUE COMMENT '出库单号',
    product_id BIGINT COMMENT '产品ID',
    product_name VARCHAR(128) COMMENT '产品名称',
    batch_no VARCHAR(64) COMMENT '批次号',
    outbound_quantity DECIMAL(15,4) COMMENT '出库数量',
    unit VARCHAR(32) COMMENT '单位',
    outbound_date DATE COMMENT '出库日期',
    outbound_type VARCHAR(32) COMMENT '出库类型',
    task_id BIGINT COMMENT '任务ID',
    plot_id BIGINT COMMENT '地块ID',
    plot_name VARCHAR(128) COMMENT '地块名称',
    applicant VARCHAR(64) COMMENT '申请人',
    approver VARCHAR(64) COMMENT '审批人',
    approval_time DATETIME COMMENT '审批时间',
    approval_status VARCHAR(32) DEFAULT 'pending' COMMENT '审批状态',
    warehouse_location VARCHAR(128) COMMENT '库位',
    purpose VARCHAR(256) COMMENT '用途',
    remark VARCHAR(512) COMMENT '备注',
    del_flag TINYINT DEFAULT 0 COMMENT '删除标记',
    tenant_id VARCHAR(64) COMMENT '租户ID',
    create_by VARCHAR(64) COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) COMMENT '更新人',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_outbound_no (outbound_no),
    INDEX idx_batch_no (batch_no),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='投入品出库表';

CREATE TABLE IF NOT EXISTS agri_prod_input_usage (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    usage_no VARCHAR(64) NOT NULL UNIQUE COMMENT '使用单号',
    product_id BIGINT COMMENT '产品ID',
    product_name VARCHAR(128) COMMENT '产品名称',
    batch_no VARCHAR(64) COMMENT '批次号',
    outbound_id BIGINT COMMENT '出库单ID',
    task_id BIGINT COMMENT '任务ID',
    task_execution_id BIGINT COMMENT '任务执行ID',
    plot_id BIGINT COMMENT '地块ID',
    plot_name VARCHAR(128) COMMENT '地块名称',
    usage_date DATE COMMENT '使用日期',
    usage_quantity DECIMAL(15,4) COMMENT '使用数量',
    unit VARCHAR(32) COMMENT '单位',
    usage_method VARCHAR(128) COMMENT '使用方法',
    dilution_ratio VARCHAR(64) COMMENT '稀释比例',
    target_pest VARCHAR(128) COMMENT '防治对象',
    weather_condition VARCHAR(128) COMMENT '天气状况',
    wind_level VARCHAR(32) COMMENT '风力等级',
    applicator VARCHAR(64) COMMENT '施药人',
    pre_harvest_interval INT COMMENT '采收间隔(天)',
    safe_harvest_date DATE COMMENT '安全采收日期',
    harvest_locked TINYINT DEFAULT 0 COMMENT '采收锁定',
    usage_result VARCHAR(512) COMMENT '使用效果',
    effectiveness_evaluation VARCHAR(512) COMMENT '效果评价',
    chain_status VARCHAR(32) DEFAULT 'pending' COMMENT '上链状态',
    chain_tx_hash VARCHAR(256) COMMENT '链上交易哈希',
    del_flag TINYINT DEFAULT 0 COMMENT '删除标记',
    tenant_id VARCHAR(64) COMMENT '租户ID',
    create_by VARCHAR(64) COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) COMMENT '更新人',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_usage_no (usage_no),
    INDEX idx_plot_id (plot_id),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='投入品使用记录表';

CREATE TABLE IF NOT EXISTS agri_prod_harvest (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    harvest_no VARCHAR(64) NOT NULL UNIQUE COMMENT '采收单号',
    farm_id BIGINT COMMENT '农场ID',
    plot_id BIGINT COMMENT '地块ID',
    plot_name VARCHAR(128) COMMENT '地块名称',
    crop_name VARCHAR(128) COMMENT '作物名称',
    variety_name VARCHAR(128) COMMENT '品种名称',
    harvest_date DATE COMMENT '采收日期',
    harvest_type VARCHAR(32) COMMENT '采收类型',
    harvest_quantity DECIMAL(15,4) COMMENT '采收数量',
    unit VARCHAR(32) COMMENT '单位',
    quality_grade VARCHAR(32) COMMENT '质量等级',
    harvest_method VARCHAR(64) COMMENT '采收方式',
    harvester VARCHAR(64) COMMENT '采收人',
    harvest_location_lat DECIMAL(12,8) COMMENT '采收地点纬度',
    harvest_location_lng DECIMAL(12,8) COMMENT '采收地点经度',
    photos_json TEXT COMMENT '照片JSON',
    status VARCHAR(32) DEFAULT 'pending' COMMENT '状态',
    warehousing_quantity DECIMAL(15,4) COMMENT '入库数量',
    qualified_rate DECIMAL(5,2) COMMENT '合格率',
    reject_quantity DECIMAL(15,4) COMMENT '不合格数量',
    reject_reason VARCHAR(512) COMMENT '不合格原因',
    chain_status VARCHAR(32) DEFAULT 'pending' COMMENT '上链状态',
    chain_tx_hash VARCHAR(256) COMMENT '链上交易哈希',
    remark VARCHAR(512) COMMENT '备注',
    del_flag TINYINT DEFAULT 0 COMMENT '删除标记',
    tenant_id VARCHAR(64) COMMENT '租户ID',
    create_by VARCHAR(64) COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) COMMENT '更新人',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_harvest_no (harvest_no),
    INDEX idx_farm_id (farm_id),
    INDEX idx_plot_id (plot_id),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='采收记录表';

CREATE TABLE IF NOT EXISTS agri_prod_inventory (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    inventory_no VARCHAR(64) NOT NULL UNIQUE COMMENT '库存编号',
    batch_no VARCHAR(64) COMMENT '批次号',
    farm_id BIGINT COMMENT '农场ID',
    product_type VARCHAR(32) COMMENT '产品类型',
    product_id BIGINT COMMENT '产品ID',
    product_name VARCHAR(128) COMMENT '产品名称',
    variety_name VARCHAR(128) COMMENT '品种名称',
    warehouse_type VARCHAR(64) COMMENT '仓库类型',
    warehouse_location VARCHAR(128) COMMENT '库位',
    quantity DECIMAL(15,4) COMMENT '数量',
    unit VARCHAR(32) COMMENT '单位',
    quality_grade VARCHAR(32) COMMENT '质量等级',
    production_date DATE COMMENT '生产日期',
    inbound_date DATE COMMENT '入库日期',
    shelf_life_days INT COMMENT '保质期(天)',
    expire_date DATE COMMENT '过期日期',
    alert_status VARCHAR(32) DEFAULT 'normal' COMMENT '预警状态',
    alert_days_before INT DEFAULT 30 COMMENT '提前预警天数',
    last_check_date DATE COMMENT '上次盘点日期',
    last_quantity DECIMAL(15,4) COMMENT '上次盘点数量',
    version INT DEFAULT 1 COMMENT '版本号',
    del_flag TINYINT DEFAULT 0 COMMENT '删除标记',
    tenant_id VARCHAR(64) COMMENT '租户ID',
    create_by VARCHAR(64) COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) COMMENT '更新人',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    remark VARCHAR(512) COMMENT '备注',
    INDEX idx_inventory_no (inventory_no),
    INDEX idx_batch_no (batch_no),
    INDEX idx_farm_id (farm_id),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='库存表';

CREATE TABLE IF NOT EXISTS agri_prod_test_task (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    task_no VARCHAR(64) NOT NULL UNIQUE COMMENT '检测任务编号',
    farm_id BIGINT COMMENT '农场ID',
    plot_id BIGINT COMMENT '地块ID',
    plot_name VARCHAR(128) COMMENT '地块名称',
    batch_no VARCHAR(64) COMMENT '批次号',
    test_type VARCHAR(64) COMMENT '检测类型',
    test_category VARCHAR(64) COMMENT '检测类别',
    test_org_id BIGINT COMMENT '检测机构ID',
    test_org_name VARCHAR(128) COMMENT '检测机构名称',
    sample_no VARCHAR(64) COMMENT '样品编号',
    sample_source VARCHAR(256) COMMENT '样品来源',
    sample_amount VARCHAR(64) COMMENT '样品数量',
    sampling_date DATE COMMENT '采样日期',
    sampler VARCHAR(64) COMMENT '采样人',
    sampling_location VARCHAR(256) COMMENT '采样地点',
    test_requirements TEXT COMMENT '检测要求',
    task_status VARCHAR(32) DEFAULT 'pending' COMMENT '任务状态',
    expected_complete_date DATE COMMENT '预计完成日期',
    actual_complete_date DATE COMMENT '实际完成日期',
    total_fee DECIMAL(12,2) COMMENT '检测费用',
    report_delivery_type VARCHAR(32) COMMENT '报告交付方式',
    del_flag TINYINT DEFAULT 0 COMMENT '删除标记',
    tenant_id VARCHAR(64) COMMENT '租户ID',
    create_by VARCHAR(64) COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) COMMENT '更新人',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    remark VARCHAR(512) COMMENT '备注',
    INDEX idx_task_no (task_no),
    INDEX idx_farm_id (farm_id),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='检测任务表';

CREATE TABLE IF NOT EXISTS agri_prod_test_record (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    record_no VARCHAR(64) NOT NULL UNIQUE COMMENT '检测记录编号',
    task_id BIGINT COMMENT '任务ID',
    batch_no VARCHAR(64) COMMENT '批次号',
    farm_id BIGINT COMMENT '农场ID',
    product_name VARCHAR(128) COMMENT '产品名称',
    test_type VARCHAR(64) COMMENT '检测类型',
    test_items_json TEXT COMMENT '检测项目JSON',
    test_results_json TEXT COMMENT '检测结果JSON',
    conclusion VARCHAR(512) COMMENT '结论',
    is_qualified TINYINT DEFAULT 0 COMMENT '是否合格',
    test_date DATE COMMENT '检测日期',
    report_no VARCHAR(64) COMMENT '报告编号',
    report_url VARCHAR(512) COMMENT '报告URL',
    test_org_name VARCHAR(128) COMMENT '检测机构名称',
    auditor VARCHAR(64) COMMENT '审核人',
    audit_time DATETIME COMMENT '审核时间',
    audit_status VARCHAR(32) DEFAULT 'pending' COMMENT '审核状态',
    chain_status VARCHAR(32) DEFAULT 'pending' COMMENT '上链状态',
    chain_tx_hash VARCHAR(256) COMMENT '链上交易哈希',
    del_flag TINYINT DEFAULT 0 COMMENT '删除标记',
    tenant_id VARCHAR(64) COMMENT '租户ID',
    create_by VARCHAR(64) COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) COMMENT '更新人',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_record_no (record_no),
    INDEX idx_task_id (task_id),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='检测记录表';

CREATE TABLE IF NOT EXISTS agri_prod_trace_code (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    trace_code VARCHAR(128) NOT NULL UNIQUE COMMENT '溯源码',
    batch_id BIGINT COMMENT '批次ID',
    batch_no VARCHAR(64) COMMENT '批次号',
    farm_id BIGINT COMMENT '农场ID',
    farm_name VARCHAR(128) COMMENT '农场名称',
    product_name VARCHAR(128) COMMENT '产品名称',
    variety_name VARCHAR(128) COMMENT '品种名称',
    quality_grade VARCHAR(32) COMMENT '质量等级',
    harvest_date DATE COMMENT '采收日期',
    production_date DATE COMMENT '生产日期',
    shelf_life_days INT COMMENT '保质期(天)',
    expire_date DATE COMMENT '过期日期',
    status VARCHAR(32) DEFAULT 'inactive' COMMENT '状态',
    activate_time DATETIME COMMENT '激活时间',
    activate_location_lat DECIMAL(12,8) COMMENT '激活位置纬度',
    activate_location_lng DECIMAL(12,8) COMMENT '激活位置经度',
    activate_location_name VARCHAR(256) COMMENT '激活位置名称',
    trace_json TEXT COMMENT '溯源数据JSON',
    chain_status VARCHAR(32) DEFAULT 'pending' COMMENT '上链状态',
    chain_tx_hash VARCHAR(256) COMMENT '链上交易哈希',
    del_flag TINYINT DEFAULT 0 COMMENT '删除标记',
    tenant_id VARCHAR(64) COMMENT '租户ID',
    create_by VARCHAR(64) COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) COMMENT '更新人',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    remark VARCHAR(512) COMMENT '备注',
    INDEX idx_trace_code (trace_code),
    INDEX idx_batch_id (batch_id),
    INDEX idx_farm_id (farm_id),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='溯源码表';

CREATE TABLE IF NOT EXISTS agri_prod_chain_record (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    record_no VARCHAR(64) NOT NULL UNIQUE COMMENT '记录编号',
    chain_type VARCHAR(32) COMMENT '上链类型',
    target_type VARCHAR(32) COMMENT '目标类型',
    target_id BIGINT COMMENT '目标ID',
    target_code VARCHAR(64) COMMENT '目标编码',
    data_hash VARCHAR(256) COMMENT '数据哈希',
    tx_hash VARCHAR(256) COMMENT '交易哈希',
    block_number BIGINT COMMENT '区块高度',
    chain_status VARCHAR(32) DEFAULT 'pending' COMMENT '上链状态',
    chain_time DATETIME COMMENT '上链时间',
    failed_reason VARCHAR(512) COMMENT '失败原因',
    retry_count INT DEFAULT 0 COMMENT '重试次数',
    next_retry_time DATETIME COMMENT '下次重试时间',
    data_json TEXT COMMENT '数据JSON',
    del_flag TINYINT DEFAULT 0 COMMENT '删除标记',
    tenant_id VARCHAR(64) COMMENT '租户ID',
    create_by VARCHAR(64) COMMENT '创建人',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_by VARCHAR(64) COMMENT '更新人',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    INDEX idx_record_no (record_no),
    INDEX idx_target_id (target_id),
    INDEX idx_chain_status (chain_status),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='区块链记录表';

CREATE TABLE IF NOT EXISTS agri_prod_chain_verify_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    log_no VARCHAR(64) NOT NULL UNIQUE COMMENT '日志编号',
    chain_record_id BIGINT COMMENT '区块链记录ID',
    target_type VARCHAR(32) COMMENT '目标类型',
    target_id BIGINT COMMENT '目标ID',
    tx_hash VARCHAR(256) COMMENT '交易哈希',
    verify_status VARCHAR(32) COMMENT '验证状态',
    verify_time DATETIME COMMENT '验证时间',
    verified_by VARCHAR(64) COMMENT '验证人',
    verify_result_json TEXT COMMENT '验证结果JSON',
    remark VARCHAR(512) COMMENT '备注',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    INDEX idx_log_no (log_no),
    INDEX idx_chain_record_id (chain_record_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='区块链验证日志表';

INSERT INTO agri_prod_task_template (template_code, template_name, template_type, crop_category, task_type, growth_stage, description, is_system, sort_order, status) VALUES
('TPL-001', '基础施肥', 'field', '粮食作物', 'fertilize', 'seedling', '作物幼苗期基础施肥作业', 1, 1, 'active'),
('TPL-002', '病虫害防治', 'field', '蔬菜', 'pest_control', 'growth', '生长期病虫害防治作业', 1, 2, 'active'),
('TPL-003', '灌溉浇水', 'field', '水果', 'irrigation', 'flowering', '花期灌溉作业', 1, 3, 'active'),
('TPL-004', '除草作业', 'field', '粮食作物', 'weed_control', 'growth', '生长期除草作业', 1, 4, 'active'),
('TPL-005', '采摘采收', 'field', '水果', 'harvest', 'mature', '成熟期采收作业', 1, 5, 'active');

INSERT INTO agri_prod_input_product (product_code, product_name, category, unit, status) VALUES
('IP-001', '复合肥NPK 15-15-15', 'fertilizer', 'kg', 'active'),
('IP-002', '尿素', 'fertilizer', 'kg', 'active'),
('IP-003', '磷酸二铵', 'fertilizer', 'kg', 'active'),
('IP-004', '生物有机肥', 'fertilizer', 'kg', 'active'),
('IP-005', '高效氯氟氰菊酯', 'pesticide', 'ml', 'active'),
('IP-006', '吡虫啉', 'pesticide', 'g', 'active'),
('IP-007', '多菌灵', 'pesticide', 'g', 'active'),
('IP-008', '氨基酸叶面肥', 'fertilizer', 'ml', 'active');

INSERT INTO agri_prod_farm (farm_code, farm_name, farm_type, legal_person, contact_phone, province, city, status, audit_status) VALUES
('FARM-001', '示范农场', 'organic', '张三', '13800138001', '山东省', '济南市', 'active', 'approved'),
('FARM-002', '绿色农业基地', 'green', '李四', '13800138002', '河南省', '郑州市', 'active', 'approved');

INSERT INTO agri_prod_plot (farm_id, plot_code, plot_name, plot_type, area) VALUES
(1, 'PLOT-001', 'A区试验田', 'field', 10.5),
(1, 'PLOT-002', 'B区温室', 'greenhouse', 2.0),
(2, 'PLOT-003', '麦田区', 'field', 50.0);

COMMIT;