CREATE TABLE IF NOT EXISTS `agri_trade_order` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `order_no` VARCHAR(64) NOT NULL COMMENT '订单编号',
    `demand_id` BIGINT NULL COMMENT '需求ID',
    `contract_id` BIGINT NULL COMMENT '合同ID',
    `buyer_id` BIGINT NOT NULL COMMENT '买家ID',
    `buyer_name` VARCHAR(100) NOT NULL COMMENT '买家名称',
    `buyer_phone` VARCHAR(20) NULL COMMENT '买家电话',
    `buyer_type` VARCHAR(20) NULL COMMENT '买家类型',
    `seller_id` BIGINT NOT NULL COMMENT '卖家ID',
    `seller_name` VARCHAR(100) NOT NULL COMMENT '卖家名称',
    `seller_phone` VARCHAR(20) NULL COMMENT '卖家电话',
    `category_id` BIGINT NULL COMMENT '商品分类ID',
    `category_name` VARCHAR(100) NULL COMMENT '商品分类名称',
    `goods_amount` DECIMAL(18,2) NULL COMMENT '商品金额',
    `freight_amount` DECIMAL(18,2) NULL COMMENT '运费金额',
    `discount_amount` DECIMAL(18,2) NULL COMMENT '优惠金额',
    `total_amount` DECIMAL(18,2) NOT NULL COMMENT '订单总金额',
    `paid_amount` DECIMAL(18,2) NULL COMMENT '已支付金额',
    `refund_amount` DECIMAL(18,2) NULL COMMENT '退款金额',
    `currency` VARCHAR(10) DEFAULT 'CNY' COMMENT '货币类型',
    `payment_method` VARCHAR(20) NULL COMMENT '支付方式',
    `payment_status` VARCHAR(20) DEFAULT 'unpaid' COMMENT '支付状态',
    `order_status` VARCHAR(20) DEFAULT 'pending' COMMENT '订单状态',
    `delivery_province` VARCHAR(50) NULL COMMENT '收货省份',
    `delivery_city` VARCHAR(50) NULL COMMENT '收货城市',
    `delivery_district` VARCHAR(50) NULL COMMENT '收货区县',
    `delivery_address` VARCHAR(500) NULL COMMENT '收货地址',
    `delivery_contact` VARCHAR(50) NULL COMMENT '收货人',
    `delivery_phone` VARCHAR(20) NULL COMMENT '收货电话',
    `delivery_deadline` DATETIME NULL COMMENT '交货截止时间',
    `logistics_id` BIGINT NULL COMMENT '物流ID',
    `logistics_no` VARCHAR(100) NULL COMMENT '物流单号',
    `logistics_status` VARCHAR(20) NULL COMMENT '物流状态',
    `sign_time` DATETIME NULL COMMENT '签约时间',
    `payment_deadline` DATETIME NULL COMMENT '付款截止时间',
    `ship_deadline` DATETIME NULL COMMENT '发货截止时间',
    `confirm_deadline` DATETIME NULL COMMENT '确认截止时间',
    `buyer_confirmed` TINYINT(1) DEFAULT 0 COMMENT '买家是否确认',
    `buyer_confirm_time` DATETIME NULL COMMENT '买家确认时间',
    `buyer_remark` VARCHAR(500) NULL COMMENT '买家备注',
    `seller_remark` VARCHAR(500) NULL COMMENT '卖家备注',
    `admin_remark` VARCHAR(500) NULL COMMENT '管理员备注',
    `source` VARCHAR(50) NULL COMMENT '订单来源',
    `dispute_id` BIGINT NULL COMMENT '纠纷ID',
    `compensation_amount` DECIMAL(18,2) NULL COMMENT '赔偿金额',
    `settle_status` VARCHAR(20) NULL COMMENT '结算状态',
    `settle_time` DATETIME NULL COMMENT '结算时间',
    `del_flag` TINYINT(1) DEFAULT 0 COMMENT '删除标记',
    `tenant_id` VARCHAR(64) NULL COMMENT '租户ID',
    `create_by` VARCHAR(64) NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` VARCHAR(64) NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `remark` VARCHAR(500) NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_order_no` (`order_no`),
    INDEX `idx_buyer_id` (`buyer_id`),
    INDEX `idx_seller_id` (`seller_id`),
    INDEX `idx_order_status` (`order_status`),
    INDEX `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='交易订单表';

CREATE TABLE IF NOT EXISTS `agri_trade_product` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `product_code` VARCHAR(64) NOT NULL COMMENT '商品编码',
    `product_name` VARCHAR(200) NOT NULL COMMENT '商品名称',
    `category_id` BIGINT NULL COMMENT '分类ID',
    `category_name` VARCHAR(100) NULL COMMENT '分类名称',
    `seller_id` BIGINT NOT NULL COMMENT '卖家ID',
    `seller_name` VARCHAR(100) NOT NULL COMMENT '卖家名称',
    `variety` VARCHAR(100) NULL COMMENT '品种',
    `origin_province` VARCHAR(50) NULL COMMENT '产地省份',
    `origin_city` VARCHAR(50) NULL COMMENT '产地城市',
    `origin_district` VARCHAR(50) NULL COMMENT '产地区县',
    `origin_address` VARCHAR(500) NULL COMMENT '产地地址',
    `spec_level` VARCHAR(50) NULL COMMENT '规格等级',
    `spec_size` VARCHAR(50) NULL COMMENT '规格大小',
    `unit` VARCHAR(20) NOT NULL COMMENT '计量单位',
    `stock_quantity` DECIMAL(18,4) DEFAULT 0 COMMENT '库存数量',
    `price_min` DECIMAL(18,4) NULL COMMENT '最低价格',
    `price_max` DECIMAL(18,4) NULL COMMENT '最高价格',
    `price` DECIMAL(18,4) NULL COMMENT '基准价格',
    `price_type` VARCHAR(20) DEFAULT 'fixed' COMMENT '价格类型',
    `min_order_quantity` DECIMAL(18,4) NULL COMMENT '最小起订量',
    `harvest_batch_no` VARCHAR(64) NULL COMMENT '采收批次号',
    `certification_json` TEXT NULL COMMENT '认证信息JSON',
    `quality_report_url` VARCHAR(500) NULL COMMENT '质检报告URL',
    `description` TEXT NULL COMMENT '商品描述',
    `video_url` VARCHAR(500) NULL COMMENT '视频URL',
    `view_count` INT DEFAULT 0 COMMENT '浏览次数',
    `favorite_count` INT DEFAULT 0 COMMENT '收藏次数',
    `inquiry_count` INT DEFAULT 0 COMMENT '询价次数',
    `match_score` DECIMAL(5,2) NULL COMMENT '匹配评分',
    `publish_status` VARCHAR(20) DEFAULT 'draft' COMMENT '发布状态',
    `audit_remark` VARCHAR(500) NULL COMMENT '审核备注',
    `audit_time` DATETIME NULL COMMENT '审核时间',
    `auditor` VARCHAR(64) NULL COMMENT '审核人',
    `valid_until` DATETIME NULL COMMENT '有效期至',
    `status` TINYINT(1) DEFAULT 1 COMMENT '状态',
    `del_flag` TINYINT(1) DEFAULT 0 COMMENT '删除标记',
    `tenant_id` VARCHAR(64) NULL COMMENT '租户ID',
    `create_by` VARCHAR(64) NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` VARCHAR(64) NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `remark` VARCHAR(500) NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_product_code` (`product_code`),
    INDEX `idx_seller_id` (`seller_id`),
    INDEX `idx_category_id` (`category_id`),
    INDEX `idx_publish_status` (`publish_status`),
    INDEX `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='交易商品表';

CREATE TABLE IF NOT EXISTS `agri_trade_demand` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `demand_no` VARCHAR(64) NOT NULL COMMENT '需求编号',
    `buyer_id` BIGINT NOT NULL COMMENT '采购商ID',
    `buyer_name` VARCHAR(100) NOT NULL COMMENT '采购商名称',
    `buyer_type` VARCHAR(20) NULL COMMENT '采购商类型',
    `category_id` BIGINT NULL COMMENT '商品分类ID',
    `category_name` VARCHAR(100) NULL COMMENT '商品分类名称',
    `variety` VARCHAR(100) NULL COMMENT '需求品种',
    `quantity` DECIMAL(18,4) NOT NULL COMMENT '需求数量',
    `unit` VARCHAR(20) NOT NULL COMMENT '计量单位',
    `price_min` DECIMAL(18,4) NULL COMMENT '最低报价',
    `price_max` DECIMAL(18,4) NULL COMMENT '最高报价',
    `delivery_province` VARCHAR(50) NULL COMMENT '配送省份',
    `delivery_city` VARCHAR(50) NULL COMMENT '配送城市',
    `delivery_district` VARCHAR(50) NULL COMMENT '配送区县',
    `delivery_address` VARCHAR(500) NULL COMMENT '配送地址',
    `delivery_deadline` DATETIME NULL COMMENT '配送截止时间',
    `quality_requirement` TEXT NULL COMMENT '质量要求',
    `certification_require` VARCHAR(500) NULL COMMENT '认证要求',
    `sample_require` TINYINT(1) DEFAULT 0 COMMENT '样品要求',
    `packaging_require` VARCHAR(500) NULL COMMENT '包装要求',
    `demand_type` VARCHAR(20) DEFAULT 'normal' COMMENT '需求类型',
    `demand_status` VARCHAR(20) DEFAULT 'pending' COMMENT '需求状态',
    `expect_response_time` DATETIME NULL COMMENT '期望响应时间',
    `match_expire_time` DATETIME NULL COMMENT '匹配截止时间',
    `response_count` INT DEFAULT 0 COMMENT '响应次数',
    `valid_until` DATETIME NULL COMMENT '有效期至',
    `del_flag` TINYINT(1) DEFAULT 0 COMMENT '删除标记',
    `tenant_id` VARCHAR(64) NULL COMMENT '租户ID',
    `create_by` VARCHAR(64) NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` VARCHAR(64) NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `remark` VARCHAR(500) NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_demand_no` (`demand_no`),
    INDEX `idx_buyer_id` (`buyer_id`),
    INDEX `idx_category_id` (`category_id`),
    INDEX `idx_demand_status` (`demand_status`),
    INDEX `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='采购需求表';

CREATE TABLE IF NOT EXISTS `agri_trade_contract` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `contract_no` VARCHAR(64) NOT NULL COMMENT '合同编号',
    `order_id` BIGINT NULL COMMENT '订单ID',
    `contract_template_id` BIGINT NULL COMMENT '合同模板ID',
    `contract_type` VARCHAR(20) DEFAULT 'sale' COMMENT '合同类型',
    `buyer_id` BIGINT NOT NULL COMMENT '买方ID',
    `buyer_name` VARCHAR(100) NOT NULL COMMENT '买方名称',
    `buyer_phone` VARCHAR(20) NULL COMMENT '买方电话',
    `seller_id` BIGINT NOT NULL COMMENT '卖方ID',
    `seller_name` VARCHAR(100) NOT NULL COMMENT '卖方名称',
    `seller_phone` VARCHAR(20) NULL COMMENT '卖方电话',
    `goods_name` VARCHAR(200) NOT NULL COMMENT '商品名称',
    `quantity` DECIMAL(18,4) NOT NULL COMMENT '数量',
    `unit` VARCHAR(20) NOT NULL COMMENT '计量单位',
    `unit_price` DECIMAL(18,4) NOT NULL COMMENT '单价',
    `total_amount` DECIMAL(18,2) NOT NULL COMMENT '总金额',
    `currency` VARCHAR(10) DEFAULT 'CNY' COMMENT '货币类型',
    `payment_method` VARCHAR(20) NULL COMMENT '付款方式',
    `payment_term` VARCHAR(100) NULL COMMENT '付款期限',
    `delivery_method` VARCHAR(20) NULL COMMENT '交货方式',
    `delivery_address` VARCHAR(500) NULL COMMENT '交货地点',
    `delivery_deadline` DATETIME NULL COMMENT '交货期限',
    `quality_standard` VARCHAR(500) NULL COMMENT '质量标准',
    `inspection_method` VARCHAR(500) NULL COMMENT '检验方法',
    `claim_term` VARCHAR(500) NULL COMMENT '索赔期限',
    `conflict_resolution` VARCHAR(500) NULL COMMENT '争议解决方式',
    `contract_content` TEXT NULL COMMENT '合同内容',
    `contract_pdf_url` VARCHAR(500) NULL COMMENT '合同PDF URL',
    `sign_status` VARCHAR(20) DEFAULT 'pending' COMMENT '签署状态',
    `buyer_sign_time` DATETIME NULL COMMENT '买方签署时间',
    `buyer_sign_url` VARCHAR(500) NULL COMMENT '买方签署文件URL',
    `seller_sign_time` DATETIME NULL COMMENT '卖方签署时间',
    `seller_sign_url` VARCHAR(500) NULL COMMENT '卖方签署文件URL',
    `contract_status` VARCHAR(20) DEFAULT 'draft' COMMENT '合同状态',
    `effective_date` DATETIME NULL COMMENT '生效日期',
    `expire_date` DATETIME NULL COMMENT '到期日期',
    `del_flag` TINYINT(1) DEFAULT 0 COMMENT '删除标记',
    `tenant_id` VARCHAR(64) NULL COMMENT '租户ID',
    `create_by` VARCHAR(64) NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` VARCHAR(64) NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `remark` VARCHAR(500) NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_contract_no` (`contract_no`),
    INDEX `idx_order_id` (`order_id`),
    INDEX `idx_buyer_id` (`buyer_id`),
    INDEX `idx_seller_id` (`seller_id`),
    INDEX `idx_contract_status` (`contract_status`),
    INDEX `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='电子合同表';

CREATE TABLE IF NOT EXISTS `agri_trade_logistics` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `logistics_no` VARCHAR(100) NOT NULL COMMENT '物流单号',
    `order_id` BIGINT NULL COMMENT '订单ID',
    `contract_id` BIGINT NULL COMMENT '合同ID',
    `carrier_id` BIGINT NULL COMMENT '承运商ID',
    `carrier_name` VARCHAR(100) NULL COMMENT '承运商名称',
    `logistics_type` VARCHAR(20) DEFAULT 'express' COMMENT '物流类型',
    `freight_amount` DECIMAL(18,2) NULL COMMENT '运费金额',
    `pickup_province` VARCHAR(50) NULL COMMENT '取货省份',
    `pickup_city` VARCHAR(50) NULL COMMENT '取货城市',
    `pickup_district` VARCHAR(50) NULL COMMENT '取货区县',
    `pickup_address` VARCHAR(500) NULL COMMENT '取货地址',
    `pickup_contact` VARCHAR(50) NULL COMMENT '取货联系人',
    `pickup_phone` VARCHAR(20) NULL COMMENT '取货电话',
    `delivery_province` VARCHAR(50) NULL COMMENT '送货省份',
    `delivery_city` VARCHAR(50) NULL COMMENT '送货城市',
    `delivery_district` VARCHAR(50) NULL COMMENT '送货区县',
    `delivery_address` VARCHAR(500) NULL COMMENT '送货地址',
    `delivery_contact` VARCHAR(50) NULL COMMENT '送货联系人',
    `delivery_phone` VARCHAR(20) NULL COMMENT '送货电话',
    `logistics_status` VARCHAR(20) DEFAULT 'pending' COMMENT '物流状态',
    `pickup_time` DATETIME NULL COMMENT '取货时间',
    `departure_time` DATETIME NULL COMMENT '发车时间',
    `arrival_time` DATETIME NULL COMMENT '到达时间',
    `sign_time` DATETIME NULL COMMENT '签收时间',
    `sign_person` VARCHAR(50) NULL COMMENT '签收人',
    `insurance_amount` DECIMAL(18,2) NULL COMMENT '投保金额',
    `tracking_json` TEXT NULL COMMENT '物流轨迹JSON',
    `del_flag` TINYINT(1) DEFAULT 0 COMMENT '删除标记',
    `tenant_id` VARCHAR(64) NULL COMMENT '租户ID',
    `create_by` VARCHAR(64) NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` VARCHAR(64) NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `remark` VARCHAR(500) NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_logistics_no` (`logistics_no`),
    INDEX `idx_order_id` (`order_id`),
    INDEX `idx_carrier_id` (`carrier_id`),
    INDEX `idx_logistics_status` (`logistics_status`),
    INDEX `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='物流信息表';

CREATE TABLE IF NOT EXISTS `agri_trade_evaluation` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `evaluation_no` VARCHAR(64) NOT NULL COMMENT '评价编号',
    `order_id` BIGINT NOT NULL COMMENT '订单ID',
    `evaluator_id` BIGINT NOT NULL COMMENT '评价人ID',
    `evaluator_name` VARCHAR(100) NOT NULL COMMENT '评价人名称',
    `evaluatee_id` BIGINT NOT NULL COMMENT '被评价人ID',
    `evaluatee_name` VARCHAR(100) NOT NULL COMMENT '被评价人名称',
    `rating_overall` INT NOT NULL COMMENT '综合评分(1-5)',
    `rating_quality` INT NULL COMMENT '质量评分(1-5)',
    `rating_service` INT NULL COMMENT '服务评分(1-5)',
    `rating_logistics` INT NULL COMMENT '物流评分(1-5)',
    `evaluation_content` TEXT NULL COMMENT '评价内容',
    `evaluation_images` TEXT NULL COMMENT '评价图片JSON',
    `evaluation_status` VARCHAR(20) DEFAULT 'show' COMMENT '评价状态',
    `reply_content` TEXT NULL COMMENT '回复内容',
    `reply_time` DATETIME NULL COMMENT '回复时间',
    `appeal_status` VARCHAR(20) DEFAULT 'none' COMMENT '申诉状态',
    `appeal_time` DATETIME NULL COMMENT '申诉时间',
    `appeal_content` TEXT NULL COMMENT '申诉内容',
    `appeal_result` VARCHAR(500) NULL COMMENT '申诉处理结果',
    `appeal_handle_time` DATETIME NULL COMMENT '申诉处理时间',
    `appeal_handler` VARCHAR(64) NULL COMMENT '申诉处理人',
    `del_flag` TINYINT(1) DEFAULT 0 COMMENT '删除标记',
    `tenant_id` VARCHAR(64) NULL COMMENT '租户ID',
    `create_by` VARCHAR(64) NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` VARCHAR(64) NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `remark` VARCHAR(500) NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_evaluation_no` (`evaluation_no`),
    UNIQUE KEY `uk_order_id` (`order_id`),
    INDEX `idx_evaluator_id` (`evaluator_id`),
    INDEX `idx_evaluatee_id` (`evaluatee_id`),
    INDEX `idx_evaluation_status` (`evaluation_status`),
    INDEX `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='信用评价表';

CREATE TABLE IF NOT EXISTS `agri_trade_dispute` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `dispute_no` VARCHAR(64) NOT NULL COMMENT '纠纷编号',
    `order_id` BIGINT NOT NULL COMMENT '订单ID',
    `contract_id` BIGINT NULL COMMENT '合同ID',
    `applicant_id` BIGINT NOT NULL COMMENT '申请人ID',
    `applicant_name` VARCHAR(100) NOT NULL COMMENT '申请人名称',
    `respondent_id` BIGINT NOT NULL COMMENT '被申请人ID',
    `respondent_name` VARCHAR(100) NOT NULL COMMENT '被申请人名称',
    `dispute_type` VARCHAR(50) NULL COMMENT '纠纷类型',
    `dispute_amount` DECIMAL(18,2) NULL COMMENT '纠纷金额',
    `claim_amount` DECIMAL(18,2) NULL COMMENT '索赔金额',
    `dispute_content` TEXT NOT NULL COMMENT '纠纷内容',
    `evidence_json` TEXT NULL COMMENT '证据材料JSON',
    `dispute_status` VARCHAR(20) DEFAULT 'pending' COMMENT '纠纷状态',
    `respond_content` TEXT NULL COMMENT '答辩内容',
    `respond_time` DATETIME NULL COMMENT '答辩时间',
    `mediation_result` VARCHAR(20) NULL COMMENT '调解结果',
    `mediation_content` TEXT NULL COMMENT '调解内容',
    `mediator` VARCHAR(64) NULL COMMENT '调解员',
    `mediation_time` DATETIME NULL COMMENT '调解时间',
    `arbitration_result` TEXT NULL COMMENT '仲裁结果',
    `arbitration_time` DATETIME NULL COMMENT '仲裁时间',
    `del_flag` TINYINT(1) DEFAULT 0 COMMENT '删除标记',
    `tenant_id` VARCHAR(64) NULL COMMENT '租户ID',
    `create_by` VARCHAR(64) NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` VARCHAR(64) NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `remark` VARCHAR(500) NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_dispute_no` (`dispute_no`),
    INDEX `idx_order_id` (`order_id`),
    INDEX `idx_applicant_id` (`applicant_id`),
    INDEX `idx_respondent_id` (`respondent_id`),
    INDEX `idx_dispute_status` (`dispute_status`),
    INDEX `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='交易纠纷表';

CREATE TABLE IF NOT EXISTS `agri_trade_match_record` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `match_no` VARCHAR(64) NOT NULL COMMENT '匹配编号',
    `demand_id` BIGINT NOT NULL COMMENT '需求ID',
    `product_id` BIGINT NOT NULL COMMENT '商品ID',
    `buyer_id` BIGINT NOT NULL COMMENT '买家ID',
    `seller_id` BIGINT NOT NULL COMMENT '卖家ID',
    `match_score` DECIMAL(5,2) NOT NULL COMMENT '匹配分数',
    `match_type` VARCHAR(20) DEFAULT 'auto' COMMENT '匹配类型',
    `match_status` VARCHAR(20) DEFAULT 'pending' COMMENT '匹配状态',
    `response_time` DATETIME NULL COMMENT '响应时间',
    `accept_time` DATETIME NULL COMMENT '接受时间',
    `reject_time` DATETIME NULL COMMENT '拒绝时间',
    `reject_reason` VARCHAR(500) NULL COMMENT '拒绝原因',
    `order_id` BIGINT NULL COMMENT '生成订单ID',
    `del_flag` TINYINT(1) DEFAULT 0 COMMENT '删除标记',
    `tenant_id` VARCHAR(64) NULL COMMENT '租户ID',
    `create_by` VARCHAR(64) NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` VARCHAR(64) NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `remark` VARCHAR(500) NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_match_no` (`match_no`),
    INDEX `idx_demand_id` (`demand_id`),
    INDEX `idx_product_id` (`product_id`),
    INDEX `idx_buyer_id` (`buyer_id`),
    INDEX `idx_seller_id` (`seller_id`),
    INDEX `idx_match_status` (`match_status`),
    INDEX `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='智能匹配记录表';

CREATE TABLE IF NOT EXISTS `agri_trade_order_item` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `order_id` BIGINT NOT NULL COMMENT '订单ID',
    `product_id` BIGINT NULL COMMENT '商品ID',
    `product_code` VARCHAR(64) NULL COMMENT '商品编码',
    `product_name` VARCHAR(200) NULL COMMENT '商品名称',
    `category_id` BIGINT NULL COMMENT '分类ID',
    `category_name` VARCHAR(100) NULL COMMENT '分类名称',
    `variety` VARCHAR(100) NULL COMMENT '品种',
    `spec_level` VARCHAR(50) NULL COMMENT '规格等级',
    `spec_size` VARCHAR(50) NULL COMMENT '规格大小',
    `unit` VARCHAR(20) NOT NULL COMMENT '计量单位',
    `quantity` DECIMAL(18,4) NOT NULL COMMENT '数量',
    `unit_price` DECIMAL(18,4) NOT NULL COMMENT '单价',
    `amount` DECIMAL(18,2) NOT NULL COMMENT '金额',
    `batch_no` VARCHAR(64) NULL COMMENT '批次号',
    `trace_code` VARCHAR(64) NULL COMMENT '溯源码',
    `del_flag` TINYINT(1) DEFAULT 0 COMMENT '删除标记',
    `tenant_id` VARCHAR(64) NULL COMMENT '租户ID',
    `create_by` VARCHAR(64) NULL COMMENT '创建人',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` VARCHAR(64) NULL COMMENT '更新人',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `remark` VARCHAR(500) NULL COMMENT '备注',
    PRIMARY KEY (`id`),
    INDEX `idx_order_id` (`order_id`),
    INDEX `idx_product_id` (`product_id`),
    INDEX `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单项表';