CREATE TABLE IF NOT EXISTS `agri_prod_farm_info` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    `farm_code` VARCHAR(64) NOT NULL UNIQUE COMMENT '农场编码',
    `farm_name` VARCHAR(128) NOT NULL COMMENT '农场名称',
    `farm_type` VARCHAR(32) COMMENT '农场类型',
    `legal_person` VARCHAR(64) COMMENT '法人',
    `contact_phone` VARCHAR(32) COMMENT '联系电话',
    `province` VARCHAR(64) COMMENT '省份',
    `city` VARCHAR(64) COMMENT '城市',
    `district` VARCHAR(64) COMMENT '区县',
    `address` VARCHAR(256) COMMENT '详细地址',
    `longitude` DECIMAL(12,8) COMMENT '经度',
    `latitude` DECIMAL(12,8) COMMENT '纬度',
    `total_area` DECIMAL(12,4) COMMENT '总面积(亩)',
    `plot_count` INT DEFAULT 0 COMMENT '地块数量',
    `farm_type_detail` VARCHAR(256) COMMENT '农场类型详情',
    `main_products` VARCHAR(512) COMMENT '主营产品',
    `certifications` VARCHAR(256) COMMENT '认证信息',
    `certification_expire_date` DATE COMMENT '认证有效期',
    `certifications_json` TEXT COMMENT '认证信息JSON',
    `logo_url` VARCHAR(512) COMMENT 'Logo URL',
    `intro` TEXT COMMENT '农场简介',
    `register_date` DATE COMMENT '注册日期',
    `audit_status` VARCHAR(32) DEFAULT 'pending' COMMENT '审核状态',
    `status` VARCHAR(32) DEFAULT 'active' COMMENT '状态',
    `tenant_id` VARCHAR(64) NOT NULL COMMENT '租户ID',
    `farm_id` VARCHAR(64) COMMENT '农场ID',
    `create_by` VARCHAR(64) COMMENT '创建人',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` VARCHAR(64) COMMENT '更新人',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标记',
    `remark` VARCHAR(512) COMMENT '备注',
    INDEX `idx_tenant_id` (`tenant_id`),
    INDEX `idx_farm_code` (`farm_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='农场信息表';

CREATE TABLE IF NOT EXISTS `agri_prod_plot_info` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    `plot_code` VARCHAR(64) NOT NULL UNIQUE COMMENT '地块编码',
    `plot_name` VARCHAR(128) NOT NULL COMMENT '地块名称',
    `farm_id` BIGINT NOT NULL COMMENT '所属农场ID',
    `farm_code` VARCHAR(64) COMMENT '农场编码',
    `area` DECIMAL(12,4) COMMENT '面积(亩)',
    `shape` VARCHAR(32) COMMENT '形状',
    `boundary` TEXT COMMENT '边界坐标(JSON)',
    `center_longitude` DECIMAL(12,8) COMMENT '中心点经度',
    `center_latitude` DECIMAL(12,8) COMMENT '中心点纬度',
    `soil_type` VARCHAR(64) COMMENT '土壤类型',
    `soil_ph` DECIMAL(4,2) COMMENT '土壤PH值',
    `soil_organic_matter` DECIMAL(8,4) COMMENT '有机质含量',
    `current_crop` VARCHAR(64) COMMENT '当前作物',
    `planting_date` DATE COMMENT '种植日期',
    `expected_harvest_date` DATE COMMENT '预计收获日期',
    `status` VARCHAR(32) DEFAULT 'active' COMMENT '状态',
    `tenant_id` VARCHAR(64) NOT NULL COMMENT '租户ID',
    `farm_id` VARCHAR(64) COMMENT '农场ID',
    `create_by` VARCHAR(64) COMMENT '创建人',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` VARCHAR(64) COMMENT '更新人',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标记',
    `remark` VARCHAR(512) COMMENT '备注',
    INDEX `idx_tenant_id` (`tenant_id`),
    INDEX `idx_farm_id` (`farm_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='地块信息表';

CREATE TABLE IF NOT EXISTS `agri_prod_task_info` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    `task_code` VARCHAR(64) NOT NULL UNIQUE COMMENT '任务编码',
    `task_name` VARCHAR(128) NOT NULL COMMENT '任务名称',
    `task_type` VARCHAR(32) COMMENT '任务类型',
    `task_type_detail` VARCHAR(128) COMMENT '任务类型详情',
    `farm_id` BIGINT NOT NULL COMMENT '农场ID',
    `farm_code` VARCHAR(64) COMMENT '农场编码',
    `plot_id` BIGINT COMMENT '地块ID',
    `plot_code` VARCHAR(64) COMMENT '地块编码',
    `crop_name` VARCHAR(64) COMMENT '作物名称',
    `task_desc` TEXT COMMENT '任务描述',
    `executor_id` BIGINT COMMENT '执行人ID',
    `executor_name` VARCHAR(64) COMMENT '执行人姓名',
    `plan_start_time` DATETIME COMMENT '计划开始时间',
    `plan_end_time` DATETIME COMMENT '计划结束时间',
    `actual_start_time` DATETIME COMMENT '实际开始时间',
    `actual_end_time` DATETIME COMMENT '实际结束时间',
    `status` VARCHAR(32) DEFAULT 'pending' COMMENT '状态',
    `priority` VARCHAR(32) DEFAULT 'normal' COMMENT '优先级',
    `input_materials` VARCHAR(512) COMMENT '投入物料',
    `input_materials_json` TEXT COMMENT '投入物料JSON',
    `expected_output` DECIMAL(12,4) COMMENT '预期产出',
    `actual_output` DECIMAL(12,4) COMMENT '实际产出',
    `quality_requirement` VARCHAR(256) COMMENT '质量要求',
    `result_photo_urls` TEXT COMMENT '成果照片URLs',
    `result_desc` TEXT COMMENT '成果描述',
    `approval_status` VARCHAR(32) DEFAULT 'pending' COMMENT '审批状态',
    `approval_comment` VARCHAR(512) COMMENT '审批意见',
    `template_id` BIGINT COMMENT '模板ID',
    `tenant_id` VARCHAR(64) NOT NULL COMMENT '租户ID',
    `farm_id` VARCHAR(64) COMMENT '农场ID',
    `create_by` VARCHAR(64) COMMENT '创建人',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` VARCHAR(64) COMMENT '更新人',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标记',
    `remark` VARCHAR(512) COMMENT '备注',
    INDEX `idx_tenant_id` (`tenant_id`),
    INDEX `idx_farm_id` (`farm_id`),
    INDEX `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='农事任务表';

CREATE TABLE IF NOT EXISTS `agri_prod_input_ledger` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    `material_code` VARCHAR(64) NOT NULL UNIQUE COMMENT '物料编码',
    `material_name` VARCHAR(128) NOT NULL COMMENT '物料名称',
    `material_type` VARCHAR(32) COMMENT '物料类型',
    `specification` VARCHAR(128) COMMENT '规格型号',
    `unit` VARCHAR(32) COMMENT '单位',
    `brand` VARCHAR(64) COMMENT '品牌',
    `supplier_id` BIGINT COMMENT '供应商ID',
    `supplier_name` VARCHAR(128) COMMENT '供应商名称',
    `batch_number` VARCHAR(64) COMMENT '批次号',
    `production_date` DATE COMMENT '生产日期',
    `expire_date` DATE COMMENT '有效期',
    `purchase_price` DECIMAL(10,2) COMMENT '采购单价',
    `storage_location` VARCHAR(128) COMMENT '存放位置',
    `initial_stock` DECIMAL(12,4) DEFAULT 0 COMMENT '初始库存',
    `current_stock` DECIMAL(12,4) DEFAULT 0 COMMENT '当前库存',
    `min_stock` DECIMAL(12,4) DEFAULT 0 COMMENT '最低库存',
    `max_stock` DECIMAL(12,4) COMMENT '最高库存',
    `status` VARCHAR(32) DEFAULT 'active' COMMENT '状态',
    `tenant_id` VARCHAR(64) NOT NULL COMMENT '租户ID',
    `farm_id` VARCHAR(64) COMMENT '农场ID',
    `create_by` VARCHAR(64) COMMENT '创建人',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` VARCHAR(64) COMMENT '更新人',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标记',
    `remark` VARCHAR(512) COMMENT '备注',
    INDEX `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='投入品台账表';

CREATE TABLE IF NOT EXISTS `agri_prod_harvest_record` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    `harvest_code` VARCHAR(64) NOT NULL UNIQUE COMMENT '采收编码',
    `farm_id` BIGINT NOT NULL COMMENT '农场ID',
    `farm_code` VARCHAR(64) COMMENT '农场编码',
    `plot_id` BIGINT COMMENT '地块ID',
    `plot_code` VARCHAR(64) COMMENT '地块编码',
    `crop_name` VARCHAR(64) NOT NULL COMMENT '作物名称',
    `harvest_date` DATE COMMENT '采收日期',
    `expected_quantity` DECIMAL(12,4) COMMENT '预计数量',
    `actual_quantity` DECIMAL(12,4) COMMENT '实际数量',
    `unit` VARCHAR(32) COMMENT '单位',
    `quality_grade` VARCHAR(32) COMMENT '质量等级',
    `storage_location` VARCHAR(128) COMMENT '存放位置',
    `harvest_method` VARCHAR(64) COMMENT '采收方式',
    `harvest_team` VARCHAR(128) COMMENT '采收团队',
    `supervisor` VARCHAR(64) COMMENT '负责人',
    `weather_condition` VARCHAR(128) COMMENT '天气情况',
    `photos` TEXT COMMENT '照片URLs',
    `notes` TEXT COMMENT '备注说明',
    `status` VARCHAR(32) DEFAULT 'pending' COMMENT '状态',
    `trace_code` VARCHAR(64) COMMENT '溯源码',
    `batch_number` VARCHAR(64) COMMENT '批次号',
    `tenant_id` VARCHAR(64) NOT NULL COMMENT '租户ID',
    `farm_id` VARCHAR(64) COMMENT '农场ID',
    `create_by` VARCHAR(64) COMMENT '创建人',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` VARCHAR(64) COMMENT '更新人',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标记',
    INDEX `idx_tenant_id` (`tenant_id`),
    INDEX `idx_farm_id` (`farm_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='采收记录表';

CREATE TABLE IF NOT EXISTS `agri_prod_inventory` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    `inventory_code` VARCHAR(64) NOT NULL UNIQUE COMMENT '库存编码',
    `harvest_id` BIGINT COMMENT '采收ID',
    `harvest_code` VARCHAR(64) COMMENT '采收编码',
    `crop_name` VARCHAR(64) COMMENT '作物名称',
    `quality_grade` VARCHAR(32) COMMENT '质量等级',
    `batch_number` VARCHAR(64) COMMENT '批次号',
    `initial_quantity` DECIMAL(12,4) DEFAULT 0 COMMENT '初始数量',
    `current_quantity` DECIMAL(12,4) DEFAULT 0 COMMENT '当前数量',
    `unit` VARCHAR(32) COMMENT '单位',
    `storage_location` VARCHAR(128) COMMENT '存放位置',
    `warehouse_code` VARCHAR(64) COMMENT '仓库编码',
    `storage_date` DATE COMMENT '入库日期',
    `expire_date` DATE COMMENT '保质期',
    `status` VARCHAR(32) DEFAULT 'active' COMMENT '状态',
    `trace_code` VARCHAR(64) COMMENT '溯源码',
    `tenant_id` VARCHAR(64) NOT NULL COMMENT '租户ID',
    `farm_id` VARCHAR(64) COMMENT '农场ID',
    `create_by` VARCHAR(64) COMMENT '创建人',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` VARCHAR(64) COMMENT '更新人',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标记',
    `remark` VARCHAR(512) COMMENT '备注',
    INDEX `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库存表';

CREATE TABLE IF NOT EXISTS `agri_prod_trace_code` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    `trace_code` VARCHAR(64) NOT NULL UNIQUE COMMENT '溯源码',
    `harvest_id` BIGINT COMMENT '采收ID',
    `harvest_code` VARCHAR(64) COMMENT '采收编码',
    `batch_number` VARCHAR(64) COMMENT '批次号',
    `product_name` VARCHAR(128) COMMENT '产品名称',
    `product_code` VARCHAR(64) COMMENT '产品编码',
    `farm_id` BIGINT COMMENT '农场ID',
    `farm_code` VARCHAR(64) COMMENT '农场编码',
    `farm_name` VARCHAR(128) COMMENT '农场名称',
    `plot_id` BIGINT COMMENT '地块ID',
    `plot_code` VARCHAR(64) COMMENT '地块编码',
    `crop_name` VARCHAR(64) COMMENT '作物名称',
    `quality_grade` VARCHAR(32) COMMENT '质量等级',
    `harvest_date` DATE COMMENT '采收日期',
    `status` VARCHAR(32) DEFAULT 'inactive' COMMENT '状态',
    `activate_time` DATETIME COMMENT '激活时间',
    `first_query_time` DATETIME COMMENT '首次查询时间',
    `query_count` INT DEFAULT 0 COMMENT '查询次数',
    `blockchain_tx_hash` VARCHAR(256) COMMENT '区块链交易哈希',
    `blockchain_block_height` BIGINT COMMENT '区块链区块高度',
    `tenant_id` VARCHAR(64) NOT NULL COMMENT '租户ID',
    `farm_id` VARCHAR(64) COMMENT '农场ID',
    `create_by` VARCHAR(64) COMMENT '创建人',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` VARCHAR(64) COMMENT '更新人',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标记',
    `remark` VARCHAR(512) COMMENT '备注',
    INDEX `idx_trace_code` (`trace_code`),
    INDEX `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='溯源码表';

CREATE TABLE IF NOT EXISTS `agri_prod_trace_record` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    `trace_code` VARCHAR(64) NOT NULL COMMENT '溯源码',
    `trace_type` VARCHAR(32) COMMENT '溯源类型',
    `trace_time` DATETIME COMMENT '溯源时间',
    `operator` VARCHAR(64) COMMENT '操作人',
    `location` VARCHAR(256) COMMENT '位置',
    `latitude` DECIMAL(12,8) COMMENT '纬度',
    `longitude` DECIMAL(12,8) COMMENT '经度',
    `content` VARCHAR(512) COMMENT '内容描述',
    `content_json` TEXT COMMENT '内容JSON',
    `photos` TEXT COMMENT '照片URLs',
    `blockchain_tx_hash` VARCHAR(256) COMMENT '区块链交易哈希',
    `sort_order` INT DEFAULT 0 COMMENT '排序号',
    `tenant_id` VARCHAR(64) NOT NULL COMMENT '租户ID',
    `farm_id` VARCHAR(64) COMMENT '农场ID',
    `create_by` VARCHAR(64) COMMENT '创建人',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_by` VARCHAR(64) COMMENT '更新人',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT DEFAULT 0 COMMENT '删除标记',
    `remark` VARCHAR(512) COMMENT '备注',
    INDEX `idx_trace_code` (`trace_code`),
    INDEX `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='溯源记录表';