server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/agri_masterdata?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    password: Agri@2024
  redis:
    database: 1

logging:
  level:
    com.agri: DEBUG